### ISSUE TITLE
Lastest update

### ISSUE THREAD

**Issue by Corendiel** [datasets/un-locode#10]
Hello,

I interested to use your service but I'm wondering if you are using the last UN update ?
I don't see on your page when is the last time your list has been updated.
Your total number of code is 102690 while on the unece website they say they have over 103034 locations.

Thanks

**Comment by rgrp** [comment]
@sabas do you have any comment here given your latest pull request :-)

I think we are at the latest data.

**Comment by sabas** [comment]
@Corendiel it's the 2015-2 version. I convert the access database to get the data in this repository...
I wonder where it comes the 334 difference. Perhaps they count also the "headers" into the file? (I remove the rows like IT, Italy and so on from the codelist)

**Comment by sabas** [comment]
Yup the difference is that. I did a quick count in Rstudio
![image](https://cloud.githubusercontent.com/assets/1304918/12646164/b4fcfa00-c5ce-11e5-844f-97733584f1bb.png)

Example of removed rows
![image](https://cloud.githubusercontent.com/assets/1304918/12646180/c6ef472c-c5ce-11e5-8352-47098d44e186.png)

Since I don't consider them proper locodes I chose to remove them

**Comment by Corendiel** [comment]
Ok thanks for you response.
Just as a suggestion, on the Okfn.org page there is no mention to the version, I realize I could have check your comments in the Code on Git but maybe you could update the Reade me for visitors who don't know Git.
Thanks again

**Comment by sabas** [comment]
@rgrp is there an issue on data.okfn.org repo for this?

**Comment by rgrp** [comment]
@sabas no - can you open one.

**Comment by sabas** [comment]
Done. This issue can be closed I think

**Comment by rgrp** [comment]
FIXED. Thanks all.
